# this file is autogenerated by .github/workflows/build-hds.yml
{
  x86_64-linux.holo-dev-server = builtins.fetchTarball {
    url = "https://github.com/r-vdp/hds-releases/releases/download/2024-02-15-111811/holo-dev-server.tar.gz";
    sha256 = "";
  };
}
