# this file is autogenerated by .github/workflows/build-hds.yml
{
  x86_64-linux.holo-dev-server = builtins.fetchurl {
    url = "https://github.com/r-vdp/hds-releases/releases/download/2024-02-13-231342/holo-dev-server";
    sha256 = "143205kwkg357maymv2si3f9hgkd7d0y36nc317hqq4d4y1mzq11";
  };
}
