# this file is autogenerated by .github/workflows/build-hds.yml
{
  x86_64-linux.holo-dev-server = builtins.fetchurl {
    url = "https://github.com/r-vdp/hds-releases/releases/download/2024-02-13-213938/holo-dev-server";
    sha256 = "0mdqa9w1p6cmli6976v4wi0sw9r4p5prkj7lzfd1877wk11c9c73";
  };
}
