# this file is autogenerated by .github/workflows/build-hds.yml
{
  nixpkgs = builtins.fetchTarball {
    url = "https://github.com/nixos/nixpkgs/archive/9f2ee8c91ac42da3ae6c6a1d21555f283458247e.tar.gz";
    sha256 = "sha256:0imgfxzq7d7l6fcgnzzjvv6ch560svcm8s8bx8vqyvf60w24ma1d";
  };
  x86_64-linux.holo-dev-server-bin = builtins.fetchTarball {
    url = "https://github.com/r-vdp/hds-releases/releases/download/2024-02-19-171315/holo-dev-server-x86_64-linux.tar.gz";
    sha256 = "sha256:1c2j8ys7x4zb0ymcalr7r19pmzikhvdg9syav5hqclaxg9ry1qn6";
  };
  aarch64-linux.holo-dev-server-bin = builtins.fetchTarball {
    url = "https://github.com/r-vdp/hds-releases/releases/download/2024-02-19-120744/holo-dev-server-aarch64-linux.tar.gz";
    sha256 = "02mc9jnk7l4i7z7bvq4x0whghgbfk4211f46bz4ravycnzzcfr9z";
  };
}
