# this file is autogenerated by .github/workflows/build-hds.yml
{
  x86_64-linux.holo-dev-server-bin = builtins.fetchTarball {
    url = "https://github.com/r-vdp/hds-releases/releases/download/2024-02-17-171302/holo-dev-server-x86_64-linux.tar.gz";
    sha256 = "0i0mzi7ds9y9hyzihlknv4zbddk76kr7kfzk7gm7la6v5mrv2pph";
  };
  aarch64-linux.holo-dev-server-bin = builtins.fetchTarball {
    url = "https://github.com/r-vdp/hds-releases/releases/download/2024-02-17-171302/holo-dev-server-aarch64-linux.tar.gz";
    sha256 = "02mc9jnk7l4i7z7bvq4x0whghgbfk4211f46bz4ravycnzzcfr9z";
  };
}
