# this file is autogenerated by .github/workflows/build-hds.yml
{
  x86_64-linux.holo-dev-server-bin = builtins.fetchTarball {
    url = "https://github.com/r-vdp/hds-releases/releases/download/2024-02-16-124530/holo-dev-server.tar.gz";
    sha256 = "12h4jb1pjbjfsd7a3cbadfchfgg582gx0zjzxmwms92222j8azpb";
  };
}
